setup: true

version: 2.1

orbs:
  continuation: circleci/continuation@0.3.1

workflows:
  setup:
    jobs:
      - continuation/continue:
          name: "Setting up continuation"
          configuration_path: "main.yml"
          parameters: /home/circleci/params.json
          filters:
            tags:
              only: /^v([0-9]*.).([0-9]*.).([0-9]*)(D|T|S|P|$)/
            branches:
              only: /.*/
          pre-steps:
            - run:
                name: "Setting up pipeline parameters for main execution"
                command: |
                  if [[ $(echo "$CIRCLE_PULL_REQUEST $CIRCLE_PULL_REQUESTS" | grep -c "pull") -gt 0 ]]; then
                    IS_PULL_REQUEST=true
                  else
                    IS_PULL_REQUEST=false
                  fi
                  echo '{ "is_pull_request": '$IS_PULL_REQUEST' }' >> /home/circleci/params.json
